# ======================================================================
# SECTION: Column Rename Mapping (original → snake_case)
# PURPOSE: Dict mapping original column names to snake_case names.
# ======================================================================

col_snake_map = {
    'ID': 'id',
    'MRN': 'mrn',
    'PatientReferralStatus': 'patient_referral_status',
    'ReferralStatusReasons': 'referral_status_reasons',
    'Initials': 'initials',
    'Age': 'age',
    'Gender': 'gender',
    'DateReferred': 'date_referred',
    'UrgentReferral': 'urgent_referral',
    'PatientType': 'patient_type',
    'VES13Score': 'ves13_score',
    'ReferralReason': 'referral_reason',
    'ReferralReasonOther': 'referral_reason_other',
    'BeingConsideredforClinicalTrial': 'being_considered_for_clinical_trial',
    'CARGtoxicityRisk': 'carg_toxicity_risk',
    'CgaCompleted': 'cga_completed',
    'TreatmentStage': 'treatment_stage',
    'PatientInitiatedReferral': 'patient_initiated_referral',
    'ReferringMD': 'referring_md',
    'ReferringSite': 'referring_site',
    'DiseaseSite': 'disease_site',
    'DiseaseOrgan': 'disease_organ',
    'DiseaseStage': 'disease_stage',
    'TreatmentIntent': 'treatment_intent',
    'TreatmentStatus': 'treatment_status',
    'CurrentTreatmentNone': 'current_treatment_none',
    'CurrentSurgery': 'current_surgery',
    'CurrentTargetedTherapy': 'current_targeted_therapy',
    'CurrentTargetedTherapyDosing': 'current_targeted_therapy_dosing',
    'CurrentRaditation': 'current_raditation',
    'CurrentSystemic': 'current_systemic',
    'CurrentChemoAgents': 'current_chemo_agents',
    'CurrentChemoDosing': 'current_chemo_dosing',
    'CurrentHormonal': 'current_hormonal',
    'CurrentImmunotherapy': 'current_immunotherapy',
    'CurrentSurveillance': 'current_surveillance',
    'CurrentSupportiveCare': 'current_supportive_care',
    'CurrentOther': 'current_other',
    'CurrentOtherSpecify': 'current_other_specify',
    'ProposedTreatment': 'proposed_treatment',
    'ProposedSurgery': 'proposed_surgery',
    'ProposedRaditation': 'proposed_raditation',
    'ProposedSystemic': 'proposed_systemic',
    'ProposedChemoAgents': 'proposed_chemo_agents',
    'ProposedChemoDosing': 'proposed_chemo_dosing',
    'ProposedTargetedTherapy': 'proposed_targeted_therapy',
    'ProposedTargetedTherapyDosing': 'proposed_targeted_therapy_dosing',
    'ProposedHormonal': 'proposed_hormonal',
    'ProposedImmunotherapy': 'proposed_immunotherapy',
    'ProposedSurveillance': 'proposed_surveillance',
    'ProposedSupportiveCare': 'proposed_supportive_care',
    'ProposedOther': 'proposed_other',
    'ProposedOtherSpecify': 'proposed_other_specify',
    'ProposedAlt1': 'proposed_alt1',
    'ProposedAlt1Surgery': 'proposed_alt1_surgery',
    'ProposedAlt1Raditation': 'proposed_alt1_raditation',
    'ProposedAlt1Systemic': 'proposed_alt1_systemic',
    'ProposedAlt1ChemoAgents': 'proposed_alt1_chemo_agents',
    'ProposedAlt1ChemoDosing': 'proposed_alt1_chemo_dosing',
    'ProposedAlt1TargetedTherapy': 'proposed_alt1_targeted_therapy',
    'ProposedAlt1TargetedTherapyDosing': 'proposed_alt1_targeted_therapy_dosing',
    'ProposedAlt1Hormonal': 'proposed_alt1_hormonal',
    'PorposedAlt1Immunotherapy': 'porposed_alt1_immunotherapy',
    'ProposedAlt1Surveillance': 'proposed_alt1_surveillance',
    'ProposedAlt1SupportiveCare': 'proposed_alt1_supportive_care',
    'ProposedAlt1Other': 'proposed_alt1_other',
    'ProposedAlt1OtherSpecify': 'proposed_alt1_other_specify',
    'ProposedAlt2': 'proposed_alt2',
    'ProposedAlt2Surgery': 'proposed_alt2_surgery',
    'ProposedAlt2Raditation': 'proposed_alt2_raditation',
    'ProposedAlt2Systemic': 'proposed_alt2_systemic',
    'ProposedAlt2ChemoAgents': 'proposed_alt2_chemo_agents',
    'ProposedAlt2ChemoDosing': 'proposed_alt2_chemo_dosing',
    'ProposedAlt2TargetedTherapy': 'proposed_alt2_targeted_therapy',
    'ProposedAlt2TargetedTherapyDosing': 'proposed_alt2_targeted_therapy_dosing',
    'ProposedAlt2Hormonal': 'proposed_alt2_hormonal',
    'ProposedAlt2Immunotherapy': 'proposed_alt2_immunotherapy',
    'ProposedAlt2Surveillance': 'proposed_alt2_surveillance',
    'ProposedAlt2SupportiveCare': 'proposed_alt2_supportive_care',
    'ProposedAlt2Other': 'proposed_alt2_other',
    'ProposedAlt2OtherSpecify': 'proposed_alt2_other_specify',
    '1stAppointmentDate': '1st_appointment_date',
    '1stAppointmentDateOffered': '1st_appointment_date_offered',
    'DelayPatientReason': 'delay_patient_reason',
    'DelayProviderReason': 'delay_provider_reason',
    'AppointmentDelayedReason': 'appointment_delayed_reason',
    'AppointmentDelayedReasonOther': 'appointment_delayed_reason_other',
    'FollowupOffered': 'followup_offered',
    'AppointmentOffered': 'appointment_offered',
    'GeriatricSyndrome': 'geriatric_syndrome',
    'Frailty': 'frailty',
    'Comorbidities': 'comorbidities',
    'FunctionalStatus': 'functional_status_org',
    'FunctionalStatusIADLs': 'functional_status_iadls',
    'FunctionalStatusPhys': 'functional_status_phys',
    'FallsRisk': 'falls_risk',
    'MedicationOptimization': 'medication_optimization',
    'SocialSupports': 'social_supports',
    'Nutrition': 'nutrition',
    'Mood': 'mood',
    'Cognition': 'cognition',
    'FrailtyRec': 'frailty_rec',
    'ComorbiditiesRec': 'comorbidities_rec',
    'FunctionalStatusRec': 'functional_status_rec',
    'FallsRiskRec': 'falls_risk_rec',
    'MedicationOptimizationRec': 'medication_optimization_rec',
    'SocialSupportsRec': 'social_supports_rec',
    'NutritionRec': 'nutrition_rec',
    'MoodRec': 'mood_rec',
    'CognitionRec': 'cognition_rec',
    'OACCRecommendation': 'oacc_recommendation',
    'OACCRecommendationOther': 'oacc_recommendation_other',
    'OACCRecommendationOtherSpecify': 'oacc_recommendation_other_specify',
    'EnhanceTrmtDelivery': 'enhance_trmt_delivery',
    'EnhanceComorbMngmt': 'enhance_comorb_mngmt',
    'EnhanceEduSupport': 'enhance_edu_support',
    'EnhanceDiseaseSymptoms': 'enhance_disease_symptoms',
    'EnhanceFutureTrmt': 'enhance_future_trmt',
    'EnhancePeriOpMgmt': 'enhance_peri_op_mgmt',
    'FinalTreatmentStatus': 'final_treatment_status',
    'TreatmentImpact': 'treatment_impact',
    'TreatmentImpactSpecify': 'treatment_impact_specify',
    'FinalTreatmentNone': 'final_treatment_none',
    'FinalTreatmentSurgery': 'final_treatment_surgery',
    'FinalTreatmentRaditation': 'final_treatment_raditation',
    'FinalTreatmentSystemic': 'final_treatment_systemic',
    'FinalTreatmentChemoAgents': 'final_treatment_chemo_agents',
    'FinalTreatmentChemoDosing': 'final_treatment_chemo_dosing',
    'FinalTreatmentTargetedTherapy': 'final_treatment_targeted_therapy',
    'FinalTreatmentTargetedTherapyDosing': 'final_treatment_targeted_therapy_dosing',
    'FinalTreatmentHormonal': 'final_treatment_hormonal',
    'FinalTreatmentImmunotherapy': 'final_treatment_immunotherapy',
    'FinalTreatmentSurveillance': 'final_treatment_surveillance',
    'FinalTreatmentSupportiveCare': 'final_treatment_supportive_care',
    'FinalTreatmentOther': 'final_treatment_other',
    'FinalTreatmentOtherSpecify': 'final_treatment_other_specify',
    'ReferredSW': 'referred_sw',
    'ReferredDietician': 'referred_dietician',
    'CCACReferral': 'ccac_referral',
    'ReferredCCAC': 'referred_ccac',
    'ReferredCCACpsw': 'referred_ccac_psw',
    'ReferredCCACsw': 'referred_ccac_sw',
    'ReferredCCACslp': 'referred_ccac_slp',
    'ReferredCCACptot': 'referred_ccac_ptot',
    'ReferredCCACnursing': 'referred_ccac_nursing',
    'ReferredCCACdietician': 'referred_ccac_dietician',
    'ReferredPsychologyPsychiatry': 'referred_psychology_psychiatry',
    'ReferredPalCare': 'referred_pal_care',
    'ReferredRehab': 'referred_rehab',
    'ReferredFallPrev': 'referred_fall_prev',
    'ReferredGeriatricDayHospital': 'referred_geriatric_day_hospital',
    'ReferredOther': 'referred_other',
    'ReferredOtherSpecify': 'referred_other_specify',
    'Notes': 'notes',
    'PatientReferralStatus': 'patient_referral_status',
    'ReferralStatusReasons': 'referral_status_reasons',
    'BeingConsideredforClinicalTrial': 'being_considered_for_clinical_trial',
    'ReferringMD': 'referring_md',
    'CARGtoxicityRisk': 'carg_toxicity_risk',
}


# ======================================================================
# SECTION: Column Tree (categories → subcategories | columns)
# PURPOSE: One nested dictionary of categories and their columns.
# ======================================================================

column_tree = {
    "identifiers": [
        "id",
        "mrn",
        "initials",
    ],

    "demographics": [
        "age",
        "gender",
    ],

    "referral": {
        "core": [
            "date_referred",
            "urgent_referral",
            "patient_type",
            "ves13_score",
            "referral_reason",
            "referral_reason_other",
            "patient_referral_status",
            "referral_status_reasons",
            "patient_initiated_referral",
            "referring_md",
            "referring_site",
            "being_considered_for_clinical_trial",
        ],
        "appointments": [
            "1st_appointment_date",
            "1st_appointment_date_offered",
            "followup_offered",
            "appointment_offered",
            "delay_patient_reason",
            "delay_provider_reason",
            "appointment_delayed_reason",
            "appointment_delayed_reason_other",
        ],
        "external_referrals": [
            "ccac_referral",
            "referred_ccac",
            "referred_ccac_psw",
            "referred_ccac_sw",
            "referred_ccac_slp",
            "referred_ccac_ptot",
            "referred_ccac_nursing",
            "referred_ccac_dietician",
            "referred_sw",
            "referred_dietician",
            "referred_psychology_psychiatry",
            "referred_pal_care",
            "referred_rehab",
            "referred_fall_prev",
            "referred_geriatric_day_hospital",
            "referred_other",
            "referred_other_specify",
        ],
    },

    "disease": [
        "disease_site",
        "disease_organ",
        "disease_stage",
    ],

    "treatment": {
        "treatment_meta": [
            "treatment_stage",
            "treatment_intent",
            "treatment_status",
        ],
        "current": [
            "current_treatment_none",
            "current_surgery",
            "current_targeted_therapy",
            "current_targeted_therapy_dosing",
            "current_raditation",
            "current_systemic",
            "current_chemo_agents",
            "current_chemo_dosing",
            "current_hormonal",
            "current_immunotherapy",
            "current_surveillance",
            "current_supportive_care",
            "current_other",
            "current_other_specify",
        ],
        "proposed": [
            "proposed_treatment",
            "proposed_surgery",
            "proposed_raditation",
            "proposed_systemic",
            "proposed_chemo_agents",
            "proposed_chemo_dosing",
            "proposed_targeted_therapy",
            "proposed_targeted_therapy_dosing",
            "proposed_hormonal",
            "proposed_immunotherapy",
            "proposed_surveillance",
            "proposed_supportive_care",
            "proposed_other",
            "proposed_other_specify",
        ],
        "proposed_alt1": [
            "proposed_alt1",
            "proposed_alt1_surgery",
            "proposed_alt1_raditation",
            "proposed_alt1_systemic",
            "proposed_alt1_chemo_agents",
            "proposed_alt1_chemo_dosing",
            "proposed_alt1_targeted_therapy",
            "proposed_alt1_targeted_therapy_dosing",
            "proposed_alt1_hormonal",
            "porposed_alt1_immunotherapy",
            "proposed_alt1_surveillance",
            "proposed_alt1_supportive_care",
            "proposed_alt1_other",
            "proposed_alt1_other_specify",
        ],
        "proposed_alt2": [
            "proposed_alt2",
            "proposed_alt2_surgery",
            "proposed_alt2_raditation",
            "proposed_alt2_systemic",
            "proposed_alt2_chemo_agents",
            "proposed_alt2_chemo_dosing",
            "proposed_alt2_targeted_therapy",
            "proposed_alt2_targeted_therapy_dosing",
            "proposed_alt2_hormonal",
            "proposed_alt2_immunotherapy",
            "proposed_alt2_surveillance",
            "proposed_alt2_supportive_care",
            "proposed_alt2_other",
            "proposed_alt2_other_specify",
        ],
        "final": [
            "final_treatment_status",
            "treatment_impact",
            "treatment_impact_specify",
            "final_treatment_none",
            "final_treatment_surgery",
            "final_treatment_raditation",
            "final_treatment_systemic",
            "final_treatment_chemo_agents",
            "final_treatment_chemo_dosing",
            "final_treatment_targeted_therapy",
            "final_treatment_targeted_therapy_dosing",
            "final_treatment_hormonal",
            "final_treatment_immunotherapy",
            "final_treatment_surveillance",
            "final_treatment_supportive_care",
            "final_treatment_other",
            "final_treatment_other_specify",
        ],
    },

    "geriatric_assessment": {
        "syndrome": [
            "geriatric_syndrome",
            "frailty",
        ],
        "domains": [
            "comorbidities",
            "functional_status_iadls",
            "functional_status_phys",
            "functional_status"
            "falls_risk",
            "medication_optimization",
            "social_supports",
            "nutrition",
            "mood",
            "cognition",
        ],
        "recommendations": [
            "comorbidities_rec",
            "functional_status_rec",
            "falls_risk_rec",
            "medication_optimization_rec",
            "social_supports_rec",
            "nutrition_rec",
            "mood_rec",
            "cognition_rec",
        ],
        "enhancements": [
            "enhance_trmt_delivery",
            "enhance_comorb_mngmt",
            "enhance_edu_support",
            "enhance_disease_symptoms",
            "enhance_future_trmt",
            "enhance_peri_op_mgmt",
        ],
        "result": [
            "cga_completed",
            "carg_toxicity_risk",
        ],
        "oacc_recommendation": [
            "oacc_recommendation",
            "oacc_recommendation_other",
            "oacc_recommendation_other_specify",
        ],
    },

    "notes": [
        "notes",
    ],
}




# ======================================================================
# SECTION: Value Maps (domains, recs, other columns)
# PURPOSE: Per-column value maps used to create mapped_<col>.
# ======================================================================

domains_map = {
    "comorbidities": {
        "Low": "normal",
        "Deferred": "normal",
        "Moderate": "abnormal",
        "High": "abnormal",
    },
    "functional_status_iadls": {
        "Independent": "normal",
        "Deferred": "normal",
        "Dependent in 1+ IADLs": "abnormal",
    },
    "functional_status_phys": {
        "Normal": "normal",
        "Deferred": "normal",
        "Decreased physical per.": "abnormal",
    },
    "falls_risk": {
        "Not increased": "normal",
        "Deferred": "normal",
        "Increased": "abnormal",
    },
    "medication_optimization": {
        "No issues": "normal",
        "Deferred": "normal",
        "Potential for optimization": "abnormal",
    },
    "social_supports": {
        "Good": "normal",
        "Deferred": "normal",
        "Vulnerable": "abnormal",
        "None": "abnormal",
    },
    "nutrition": {
        "Normal": "normal",
        "Deferred": "normal",
        "At risk": "abnormal",
        "Malnourished": "abnormal",
    },
    "mood": {
        "Normal": "normal",
        "Unable to assess fully": "normal",
        "Deferred": "normal",
        "Depressed": "abnormal",
    },
    "cognition": {
        "Normal": "normal",
        "Borderline/Req. further testing": "normal",
        "Deferred": "normal",
        "Abnormal": "abnormal",
    },
}

recs_map = {
    "No recommendations": "no/deferred recommendations",
    "Recommendations deferred": "no/deferred recommendations",
    "Recommendations made": "recommendations made",
    "Currently being addressed": "currently being addressed",
    "": None,
    None: None,
}


other_cols_map = {
    "treatment_impact": {
        "Treatment intensity reduced": "treatment changed",
        "Supportive care only": "treatment changed",
        "Treatment intensified": "treatment changed",
        "Treatment deferred": "treatment changed",
        "Treatment unchanged": "treatment unchanged",
    },
    "disease_site": {
        "GI": "gastrointestinal",
        "GU": "genitourinary",
        "Head & Neck": "head and neck",
        "GYNE": "gynecologic",
        "Lymphoma": "lymphoma",
        "Thoracic": "thoracic",
        "Breast": "breast",
        "Myeloma": "myeloma",
        "Leukemia": "leukemia",
        "Melanoma": "melanoma",
        "Sarcoma": "sarcoma",
        "Thyroid": "thyroid",
        "Other": "other",
        "Skin (not melanoma)": "skin non-melanoma",
        "CNS": "central nervous system",
        "Eye": "eye",
    },
}

hematologic_sites = ['Leukemia', 'Lymphoma', 'Myeloma']





typo_corrections = {
    "endometial": "endometrial",
    "endometium": "endometrium",
    "gastic dlbcl": "gastric DLBCL",
    "gastro-esophageal": "gastroesophageal",
    "heptocellular": "hepatocellular",
    "colon- polyp": "colon polyp",
    "neuroendcrine": "neuroendocrine",
    "plemorphic adenoma": "pleomorphic adenoma",
    "hcc & pancreas": "HCC and pancreas",
    "gastric/ge junction": "gastric and GE junction",
    "ampullary/distal cholangiocarcinoma": "ampullary and distal cholangiocarcinoma",
    "appendix/lower gi large mass": "appendix and lower GI large mass",
    "urothelial & prostate": "urothelial and prostate",
    "ge junction (esophageal) adenocarcinoma": "GE junction adenocarcinoma"
}